[project]
name = "auth_api"
version = "0.1.0"
description = "Flask Auth API implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "flask-jwt-extended>=4.7.1",
    "sqlmodel>=0.0.24",
]
